### ISSUE TITLE
Activity.Current is null when processing CAP listener

### ISSUE THREAD

**Issue by WillPhoenixLiu** [yang-xiaodong/OpenTracing.Contrib.CAP#1]
We're trying to write tracing info of our system. It works fine with http requests and sql queries.
We always get the following message after publish a message.
No ActiveSpan. Event: CapDiagnosticListener/DotNetCore.CAP.WritePublishAfter

After the debug, it turns out the Activity.Current is null, so it will not step into the HandleActivityStart method.
I guess it has something to do with the DiagnosticSource implementation.
@yang-xiaodong  Do you any idea what's the root cause?

**Comment by yang-xiaodong** [comment]
`Activity` is different part with `DiagnosticSource`, It's not standard relative to opentracing, so we don't use it

**Comment by WillPhoenixLiu** [comment]
Do you have any plan to support with opentracing?
CAP is base on .net core, we usually use the contribution lib opentracing.netcore. And the opentracing.netcore lib is base on the Activity. I don't think it has something to do with standard of opentracing.
